### ISSUE TITLE
Windows emacs can't handle filenames with angle brackets

### ISSUE THREAD

**Issue by JamesB797** [mpenet/clojure-snippets#14]
When spacemacs on Windows tries to install clojure-snippets, it fails on '->', since Windows can't create filenames with angle brackets in them. I'm also unable to checkout the repo for the same reason. I would like to have snippets for Clojure, but I'm also not looking forward to writing elisp to install just the snippets without angle brackets.

I don't know whether the maintainer wants to support windows or not, but if you weren't aware of this issue, now you are :).

**Comment by dotemacs** [comment]
Hello @JamesB797 

thank you for bringing this to light.

I have nothing against the snippet file in question being renamed to something more appropriate, say **thread-first** and **thread-last**, since I'm guessing, it affects both of them:

https://github.com/mpenet/clojure-snippets/blob/master/snippets/clojure-mode/-%3E
https://github.com/mpenet/clojure-snippets/blob/master/snippets/clojure-mode/-%3E%3E 

@mpenet what do you think?

Should @JamesB797 create a **pull request** with the changes?

Thank you

**Comment by mpenet** [comment]
Hi,

**Comment by mpenet** [comment]
Hi, 

For now I reverted the commit since it breaks a few things. I would say we should maybe just look for another shortcut. I personally favor 2-3 ascii letters over keys that require modifiers, could be `tf` `tl' for instance (thread first, thread last).

**Comment by dotemacs** [comment]
@JamesB797 can you please confirm that the latest changes resolve the issue for you? 

Thanks

**Comment by JamesB797** [comment]
Yes it installs fine now for me.

**Comment by dotemacs** [comment]
Great, thanks

I'll close the issue then
